#:schema ./shared/pitchfork.schema.json

[daemons.caddy]
run = "mise caddy"
auto = ["start"]
boot_start = true

[daemons.caddy.cron]
schedule = "0 */1 * * *"
retrigger = "always"

[daemons.db]
run = "mise //apps/db:dev"
auto = ["start"]
cron = { schedule = "0 */1 * * *", retrigger = "finish" }

[daemons.book]
run = "mise //pkgs/ui:book"
auto = ["start"]
ready_output = "Storybook ready"
cron = { schedule = "0 */1 * * *", retrigger = "finish" }

[daemons.speedtest]
run = "./bin/speedtest.sh"
auto = ["start"]

[daemons.speedtest.cron]
schedule = "0/15 * * * *"
retrigger = "always"
