#:schema https://pitchfork.jdx.dev/schema.json

[daemons.caddy]
run = "mise caddy"
auto = ["start"]
boot_start = true

[daemons.db]
run = "mise //apps/db:dev"
auto = ["start"]

[daemons.book]
run = "mise //pkgs/ui:book"
ready_port = 6006
auto = ["start"]
ready_output = "Storybook ready"
