#:schema ./shared/pitchfork.schema.json

[daemons.caddy]
run = "mise caddy"
auto = ["start"]
boot_start = true

[daemons.caddy.cron]
schedule = "0 */1 * * *"
retrigger = "always"

[daemons.db]
run = "mise //apps/db:dev"
auto = ["start"]
cron = { schedule = "0 */1 * * *", retrigger = "finish" }

