[tools]
"ubi:pocketbase/pocketbase" = "latest"

[settings.sops]
rops = false
age_key_file = "../../dev-age-id.key"
age_recipients = "age1yubikey1q2ku8pcyj4vnjs34lfzrw6q54z96anuxj69p3dpeyz9n7aa58733s58w20p"

[env]
SOPS_AGE_KEY_FILE = "../../dev-age-id.key"
'_'.file = [
  { path = "../../.env.yaml" },
]

[tasks]
dev = 'pocketbase serve --dev --hooksWatch'
pb = 'pocketbase'
