[tasks.build]
run = "cargo build"

[tasks.cargo]
run = "cargo"

[tasks.docs]
run = "cargo doc --no-deps --open"

[tasks.test]
run = "cargo watch -qcx test"

[tasks.dev]
run = "cargo watch -qcx run"

[tasks.run]
run = "cargo run -qp anet"
