[tools]
lua = "latest"

[settings.sops]
rops = false
age_key_file = "~/.config/wes/dev/dev-age-id.key"
age_recipients = "age1yubikey1q2ku8pcyj4vnjs34lfzrw6q54z96anuxj69p3dpeyz9n7aa58733s58w20p"

[env]
SOPS_AGE_KEY_FILE = "../../dev-age-id.key"
PROJECT_ROOT = "{{config_root}}"
SAVE_DIR = "{{config_root}}/saves"

[env._.file]
paths = [
  "~/.config/wes/dev/wes-env.yaml",
  "../../.env.yaml",
  ".env.yaml",
  ".env",
]
redact = true

[task_config]
includes = [".tasks"]

[tasks.genTypes]
run = "dx fmtk luals-addon"

[tasks.test]
run = "echo $FACTORIO_HOME $MOD_DIR $OUTPUT_DIR"
